[package]
name = "ray"
version = "0.1.0"
edition = "2021"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

# Packages that are part of lighthouse (e.g. types, eth2_ssz) are used in this package.
# NOTE: we are using the forked one due to the package visibility.
# see https://github.com/ackintosh/lighthouse/pull/4

[dependencies]
delay_map = "0.1.2"
discv5 = "0.1.0"
futures = "0.3.25"
hex = "0.4.3"
libp2p = { version = "0.49.0", default-features = false, features = ["dns-tokio", "ecdsa", "noise", "mplex", "secp256k1", "tcp-tokio", "yamux"] }
lru = "0.9.0"
parking_lot = "0.12.1"
primitive-types = "0.12.1"
serde_yaml = "0.9.16"
smallvec = "1.10.0"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tokio = { version = "1.24.0", features = ["full"] }
tokio-io-timeout = "1.2.0"
# NOTE: Build fails if we upadte tokio-util >= 0.7.0.
# -> RpcProtocol::upgrade_inbound()
# https://github.com/tokio-rs/tokio/blob/master/tokio-util/CHANGELOG.md
tokio-util = { version = "=0.6.10", features = ["codec", "compat"] }
tracing = "0.1"
tracing-subscriber = "0.3"
void = "1.0.2"

# Switched to the forked version so use the codec implemented in lighthouse.
# SEE: https://github.com/ackintosh/lighthouse/compare/unstable...ackintosh:lighthouse:publish-codec
lighthouse_network = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
beacon_node = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
environment = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
eth2_network_config = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
eth2_ssz = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
eth2_ssz_derive = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
slot_clock = { git = "https://github.com/ackintosh/lighthouse", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
types = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }

[build-dependencies]
zip = "0.6.3"

[patch]
[patch.crates-io]
# Download these crates from GitHub because latest version of these, depened by `types` crate, are not published on crates.io.
# SEE: https://github.com/sigp/lighthouse/issues/3166
eth2_ssz = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
eth2_ssz_types = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
eth2_hashing = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
tree_hash = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
tree_hash_derive = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }
eth2_serde_utils = { git = "https://github.com/ackintosh/lighthouse.git", rev = "9b2ef905171d11ff866f3590b7332871b80fc0df" }


