[package]
name = "ray"
version = "0.1.0"
edition = "2021"
rust-version = "1.61"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
# NOTE: Specifying the latest revision. This should be updated once the next version is released.
discv5 = { git = "https://github.com/sigp/discv5.git", rev = "878ef13378017bd8e5bf6426f23c3bf02f9e427d" }
futures = "0.3.7"
# Switched to the forked version so use the codec implemented in lighthouse.
# SEE: https://github.com/ackintosh/lighthouse/pull/4
lighthouse_network = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
primitive-types = "0.11.1"
serde_yaml = "0.8.26"
smallvec = "1.9.0"
types = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
eth2_ssz = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
eth2_ssz_derive = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.20.0", features = ["full"] }
tokio-io-timeout = "1.2.0"
# NOTE: Build fails if we upadte tokio-util >= 0.7.0.
# -> RpcProtocol::upgrade_inbound()
# https://github.com/tokio-rs/tokio/blob/master/tokio-util/CHANGELOG.md
tokio-util = { version = "=0.6.10", features = ["codec", "compat"] }
void = "1.0.2"

libp2p = { version = "0.46.1", default-features = false, features = ["dns-tokio", "noise", "mplex", "secp256k1", "tcp-tokio", "yamux"] }

[build-dependencies]
zip = "0.6.2"

[patch]
[patch.crates-io]
# Download these crates from GitHub because latest version of these, depened by `types` crate, are not published on crates.io.
# SEE: https://github.com/sigp/lighthouse/issues/3166
eth2_ssz = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
eth2_ssz_types = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
eth2_hashing = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
tree_hash = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
eth2_serde_utils = { git = "https://github.com/ackintosh/lighthouse.git", rev = "2b05246383ab5b7576db34a05ed5965593d4b786" }
