[package]
name = "ray"
version = "0.1.0"
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discv5 = "0.1.0-beta.12"
enr = { version = "0.5.1", features = ["ed25519", "k256"] }
futures = "0.3.7"
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tracing = "0.1"
tracing-subscriber = "0.2"
tokio = { version = "1.10.0", features = ["full"] }
void = "1.0.2"

libp2p = { version = "0.40.0-rc.2", features = ["dns-tokio", "tcp-tokio"] }
# TODO: remove the rev-reference and go back to release versions once there is a release that
# includes the following PR:
#
# https://github.com/libp2p/rust-libp2p/pull/2175
#[dependencies.libp2p]
#version = "0.39.1"
#default-features = false
#git = "https://github.com/libp2p/rust-libp2p"
#rev = "ce23cbe76a0382b6fcb0e49f1b2612df86f6465d"
#features = ["websocket", "identify", "mplex", "yamux", "noise", "gossipsub", "dns-tokio", "tcp-tokio"]
