[package]
name = "ray"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
discv5 = "0.1.0-beta.13"
futures = "0.3.7"
# Switched to the forked version so use the codec implemented in lighthouse.
# SEE: https://github.com/ackintosh/lighthouse/pull/4
lighthouse_network = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
primitive-types = "0.11.1"
serde_yaml = "0.8.24"
smallvec = "1.8.0"
types = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
eth2_ssz = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
eth2_ssz_derive = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
tiny-keccak = { version = "2.0.2", features = ["keccak"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio = { version = "1.18.2", features = ["full"] }
tokio-io-timeout = "1.2.0"
# NOTE: Build fails if we upadte tokio-util >= 0.7.0.
# -> RpcProtocol::upgrade_inbound()
# https://github.com/tokio-rs/tokio/blob/master/tokio-util/CHANGELOG.md
tokio-util = { version = "=0.6.9", features = ["codec", "compat"] }
void = "1.0.2"

libp2p = { version = "0.44.0", features = ["dns-tokio", "tcp-tokio"] }

[build-dependencies]
zip = "0.6.2"

[patch]
[patch.crates-io]
# Download these crates from GitHub because latest version of these, depened by `types` crate, are not published on crates.io.
# SEE: https://github.com/sigp/lighthouse/issues/3166
eth2_ssz = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
eth2_ssz_types = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
eth2_hashing = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
tree_hash = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
eth2_serde_utils = { git = "https://github.com/ackintosh/lighthouse.git", rev = "7048b1bdab41e3cde28bb44ac3bc25c106b9d027" }
